name: 'Setup Terragrunt'
description: 'Sets up Terragrunt CLI in your GitHub Actions workflow.'
author: 'bokeneko'
inputs:
  terragrunt_version:
    description: 'The version of Terragrunt CLI to install. A value of `latest` will install the latest version of Terragrunt CLI. Defaults to `latest`.'
    default: 'latest'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
